# ~/.config/supercommit.toml

# Which model to use for commit‑message generation
provider = "ollama"
server = "http://localhost:11434"
model = "gemma3:latest"

# Commit‑message style
[conventional]
enabled = true
types = ["feat","fix","docs","chore"]
    
# Gitmoji support
[gitmoji]
enabled = true